# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
encoding: utf-8
title: Keep calm and DevOps
email: jamiecressey89@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Musings of Jamie Cressey a DevOps advocate currently working for GameSparks.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jamiecressey.com" # the base hostname & protocol for your site
github_username: JamieCressey
twitter_username: JamieCressey

permalink: /:year/:month/:day/:title/

# Build settings

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge

gems:
  - jekyll-sitemap
  - jekyll-press

jekyll-press:
  exclude: 'feed.xml' # Exclude files from processing - file name, glob pattern or array of file names and glob patterns
  js_options: {}      # js minifier options
  css_options: {}     # css minifier options
  html_options: {}    # html minifier options

google_analytics: UA-65933410-1

exclude:
  - deploy.sh
  - s3_website.yml
  - Gemfile
  - Gemfile.lock

disqus: jamiecressey
